inherit_gem:
  rubocop-config: default.yml

AllCops:
  NewCops: enable
  SuggestExtensions: False
  TargetRubyVersion: 2.7

Layout/LineLength:
  Exclude:
    - test/**/*_test.rb

Naming/FileName:
  Exclude:
    - lib/rack-link_headers.rb
