language: ruby
rvm:
  - 2.0.0
  - 1.9.3
env:
  - GEM=ac
  - GEM=ap
gemfile:
  - gemfiles/Gemfile.rails-3-2
  - gemfiles/Gemfile.rails-4-0
  - gemfiles/Gemfile.rails-head
matrix:
  allow_failures:
  - gemfile: gemfiles/Gemfile.rails-head
