name: test
on: [push]
jobs:
  rspec:
    name: Ruby ${{ matrix.ruby }} / ${{ matrix.gemfile }}
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        ruby:
          - "3.3"
          - "3.2"
          - "3.1"
          - "3.0"
          - "2.7"
        gemfile:
          - rack_1.gemfile
          - rack_2.gemfile
          - rack_3.gemfile
        include:
          - ruby: "3.3"
            gemfile: actionpack_7.2.gemfile
            enable_actionpack: true
          - ruby: "3.2"
            gemfile: actionpack_7.1.gemfile
            enable_actionpack: true
          - ruby: "3.1"
            gemfile: actionpack_7.0.gemfile
            enable_actionpack: true
          - ruby: "3.0"
            gemfile: actionpack_7.0.gemfile
            enable_actionpack: true
          - ruby: "2.7"
            gemfile: actionpack_6.1.gemfile
            enable_actionpack: true
      fail-fast: false

    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}
      BUNDLE_WITHOUT: development
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3

    steps:
      - uses: actions/checkout@master

      - name: Install dependencies
        run: |
          sudo apt-get install --quiet --yes libsqlite3-dev

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: True

      - name: Run rake test
        env:
          ACTIONPACK: ${{ matrix.enable_actionpack }}
        run: bundle exec rake test

  rubocop:
    name: rubocop
    runs-on: ubuntu-24.04

    env:
      BUNDLE_WITHOUT: development

    steps:
      - uses: actions/checkout@master
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.2"
          bundler-cache: True
        env:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3

      - run: bundle exec rubocop --parallel --fail-level E
